import { Link } from "wouter";
import { LogIn, LogOut, ShieldCheck, ShoppingBag, UserRound } from "lucide-react";
import { startLogin } from "@/const";
import { CartDrawer, StoreFooter, StoreHeader } from "@/components/storefront";
import { useAuth } from "@/_core/hooks/useAuth";

export default function Account() {
  const { user, loading, isAuthenticated, logout } = useAuth();
  return <div className="min-h-screen bg-[#fcfbf8]"><StoreHeader /><main className="container py-16 sm:py-24"><div className="mx-auto max-w-2xl rounded-[2rem] border border-stone-200 bg-white p-7 shadow-sm sm:p-10"><p className="text-[10px] font-black uppercase tracking-[0.18em] text-[#a76c45]">Your account</p>{loading ? <div className="mt-5 space-y-3"><div className="h-8 w-2/3 animate-pulse rounded bg-stone-100" /><div className="h-4 w-full animate-pulse rounded bg-stone-100" /></div> : !isAuthenticated ? <><h1 className="mt-3 font-serif text-4xl font-black">Welcome back</h1><p className="mt-4 max-w-lg text-sm leading-7 text-stone-600">Sign in to manage your account and keep your shopping experience connected across visits.</p><button onClick={startLogin} className="mt-7 inline-flex items-center gap-2 rounded-full bg-stone-900 px-5 py-3 text-xs font-black uppercase tracking-[0.12em] text-white hover:bg-[#a76c45]"><LogIn size={15} /> Sign in</button></> : <><div className="mt-6 flex items-center gap-4"><div className="grid h-14 w-14 place-items-center rounded-full bg-[#f2eee7] text-[#a76c45]"><UserRound size={25} /></div><div><h1 className="font-serif text-3xl font-black">{user?.name || "Your profile"}</h1><p className="text-sm text-stone-500">{user?.email || "Signed in customer"}</p></div></div><div className="mt-8 grid gap-3 sm:grid-cols-2"><Link href="/shop" className="rounded-2xl border border-stone-200 p-5 hover:border-[#a76c45]"><ShoppingBag className="text-[#a76c45]" size={20} /><p className="mt-4 font-serif text-xl font-black">Continue shopping</p><p className="mt-1 text-xs leading-5 text-stone-500">Browse current product collections.</p></Link>{user?.role === "admin" && <Link href="/admin" className="rounded-2xl border border-stone-200 p-5 hover:border-[#a76c45]"><ShieldCheck className="text-[#a76c45]" size={20} /><p className="mt-4 font-serif text-xl font-black">Administration</p><p className="mt-1 text-xs leading-5 text-stone-500">Open protected operational controls.</p></Link>}</div><button onClick={() => logout()} className="mt-8 inline-flex items-center gap-2 text-xs font-black uppercase tracking-[0.12em] text-stone-500 hover:text-rose-600"><LogOut size={14} /> Sign out</button></>}</div></main><StoreFooter /><CartDrawer /></div>;
}
