import React, { useEffect, useMemo, useState } from "react";
import { ArrowRight, ChevronLeft, ChevronRight, Clock3, Leaf, Sparkles } from "lucide-react";
import { Link } from "wouter";
import { CartDrawer, categories, HERO_IMAGE, ProductGrid, ProductSkeletonGrid, shopHref, StoreFooter, StoreHeader, TrustBar } from "@/components/storefront";
import { trpc } from "@/lib/trpc";

const heroSlides = [
  { brand: "The Ordinary", title: "Healthy skin starts with a gentle ritual.", note: "Thoughtful formulas and dependable essentials for every day." },
  { brand: "Anua", title: "Care for your skin. Feel at home in it.", note: "Comforting textures made for balanced, calm routines." },
  { brand: "Cosrx", title: "Simple steps. Visible confidence.", note: "Smart everyday care, chosen for the moments that matter." },
  { brand: "Maybelline", title: "Colour that keeps your look effortless.", note: "Easy, expressive make-up for your own kind of glow." },
  { brand: "Sheglam", title: "Meet the playful side of your routine.", note: "Soft-focus beauty essentials, ready when you are." },
];

function useCountdown() {
  const target = useMemo(() => Date.now() + 1000 * 60 * 60 * 14, []);
  const [remaining, setRemaining] = useState(target - Date.now());
  useEffect(() => { const timer = window.setInterval(() => setRemaining(Math.max(0, target - Date.now())), 1000); return () => window.clearInterval(timer); }, [target]);
  const total = Math.floor(remaining / 1000);
  return { hours: String(Math.floor(total / 3600)).padStart(2, "0"), minutes: String(Math.floor((total % 3600) / 60)).padStart(2, "0"), seconds: String(total % 60).padStart(2, "0") };
}

function CatalogueRecovery({ onRetry }: { onRetry: () => void }) {
  return <div className="noura-card rounded-2xl px-6 py-12 text-center"><Sparkles size={24} className="mx-auto text-[#697b3c]" /><p className="mt-4 text-xl font-semibold text-[#253a28]">Your edit is taking a moment.</p><p className="mx-auto mt-2 max-w-md text-sm leading-6 text-[#667567]">The live catalogue could not be refreshed just now. Your bag remains safe while you retry.</p><button onClick={onRetry} className="noura-button-primary mt-6 px-5 py-3 text-xs font-black uppercase tracking-[0.12em]">Refresh the edit</button></div>;
}

export default function Home() {
  const catalogue = trpc.commerce.products.list.useQuery({ first: 12 });
  const products = catalogue.data ?? [];
  const [slide, setSlide] = useState(0);
  const countdown = useCountdown();
  useEffect(() => { const timer = window.setInterval(() => setSlide(current => (current + 1) % heroSlides.length), 5200); return () => window.clearInterval(timer); }, []);
  const active = heroSlides[slide];
  const featured = products.filter(product => product.tags.includes("Featured"));
  const flashSale = products.filter(product => product.tags.includes("Flash Sale"));
  const categoryCounts = useMemo(() => Object.fromEntries(categories.map(category => [category, products.filter(product => product.productType === category || product.tags.includes(category)).length])), [products]);
  const productsForSection = (items: typeof products) => items.length ? items : products;

  return <div className="min-h-screen bg-[#fcfdf9]"><StoreHeader /><main>
    <section className="container pt-5 sm:pt-7"><div className="grid overflow-hidden rounded-2xl border border-[#dce6d7] bg-[#eef4e9] md:min-h-[570px] md:grid-cols-[0.93fr_1.07fr]"><div className="noura-reveal relative z-10 flex min-h-[445px] flex-col justify-center px-7 py-12 sm:px-12 md:min-h-[570px] md:px-14"><div className="mb-6 flex items-center gap-2 text-[10px] font-extrabold uppercase tracking-[0.2em] text-[#4f744c]"><Leaf size={14} /> Everyday skincare, considered</div><p className="text-sm font-semibold uppercase tracking-[0.15em] text-[#59775b]">{active.brand}</p><h1 className="mt-4 max-w-xl text-5xl font-semibold leading-[0.98] tracking-[-0.055em] text-[#253a28] sm:text-6xl">{active.title}</h1><p className="mt-6 max-w-sm text-sm leading-6 text-[#607161]">{active.note}</p><Link href="/shop" className="mt-8 inline-flex w-fit items-center gap-2 rounded-lg bg-[#253a28] px-5 py-3 text-xs font-extrabold uppercase tracking-[0.11em] text-white transition hover:bg-[#4f744c]">Shop collection <ArrowRight size={15} /></Link><div className="mt-10 flex items-center gap-2"><span className="text-[10px] font-bold uppercase tracking-[0.15em] text-[#59775b]">01 — 05</span><div className="h-px flex-1 max-w-28 bg-[#b9ceb3]" />{heroSlides.map((item, index) => <button key={item.brand} aria-label={`Show ${item.brand}`} onClick={() => setSlide(index)} className={`h-2 rounded-full transition ${index === slide ? "w-7 bg-[#4f744c]" : "w-2 bg-[#b9ceb3]"}`} />)}</div></div><div className="relative min-h-[360px] overflow-hidden border-t border-[#dce6d7] bg-[#ddebd6] md:min-h-0 md:border-l md:border-t-0" style={{ backgroundImage: `linear-gradient(145deg, rgba(238,244,233,.08), rgba(72,104,70,.16)), url(${HERO_IMAGE})`, backgroundSize: "cover", backgroundPosition: "center" }}><div className="absolute inset-0 bg-gradient-to-t from-[#253a28]/25 via-transparent to-[#fcfdf9]/10" /><div className="absolute bottom-5 right-5 flex gap-2"><button onClick={() => setSlide((slide + heroSlides.length - 1) % heroSlides.length)} className="grid h-10 w-10 place-items-center rounded-lg border border-white/60 bg-white/90 text-[#253a28] shadow-sm hover:bg-white" aria-label="Previous slide"><ChevronLeft size={18} /></button><button onClick={() => setSlide((slide + 1) % heroSlides.length)} className="grid h-10 w-10 place-items-center rounded-lg bg-[#253a28] text-white shadow-sm hover:bg-[#4f744c]" aria-label="Next slide"><ChevronRight size={18} /></button></div></div></div></section>
    <TrustBar />
    <section className="container py-16 sm:py-24"><div className="grid gap-8 border-b border-[#dce6d7] pb-10 md:grid-cols-[1fr_auto] md:items-end"><div><p className="noura-eyebrow">Limited skincare edit</p><h2 className="mt-3 text-4xl font-semibold tracking-[-0.05em] text-[#253a28] sm:text-5xl">A little care goes a long way.</h2><p className="mt-4 max-w-md text-sm leading-6 text-[#667567]">Daily essentials selected to make your routine feel clear, calm, and easy to return to.</p></div><div className="flex items-center gap-2 text-[#425d43]"><Clock3 size={18} /><span className="mr-1 text-[10px] font-extrabold uppercase tracking-[0.14em]">Ends in</span>{Object.entries(countdown).map(([label, value]) => <div key={label} className="min-w-12 rounded-lg border border-[#d5e3ce] bg-white px-2 py-2 text-center"><b className="block text-base leading-4 text-[#253a28]">{value}</b><span className="text-[8px] uppercase tracking-[0.1em] text-[#668067]">{label}</span></div>)}</div></div><div className="mt-10">{catalogue.isLoading ? <ProductSkeletonGrid label="Curating products…" /> : catalogue.error ? <CatalogueRecovery onRetry={() => catalogue.refetch()} /> : <ProductGrid products={productsForSection(flashSale)} />}</div><Link href="/shop" className="mt-10 inline-flex items-center gap-2 text-xs font-extrabold uppercase tracking-[0.14em] text-[#253a28] hover:text-[#4f744c]">Shop all products <ArrowRight size={14} /></Link></section>
    <section className="noura-section border-y border-[#dce6d7] py-16 sm:py-24"><div className="container"><div className="max-w-xl"><p className="noura-eyebrow">Build your routine</p><h2 className="mt-3 text-4xl font-semibold tracking-[-0.05em] text-[#253a28] sm:text-5xl">Find what your skin needs.</h2><div className="noura-botanical-rule mt-7 max-w-sm" /></div><div className="mt-10 grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{categories.map((category, index) => <Link href={shopHref(category)} key={category} className="group relative min-h-36 overflow-hidden rounded-xl border border-[#d7e5d0] bg-white p-5 transition hover:-translate-y-1 hover:border-[#9fbe99] hover:shadow-lg"><span className="absolute right-4 top-4 text-4xl font-semibold tracking-[-0.08em] text-[#edf3e8] group-hover:text-[#d4e6cb]">0{index + 1}</span><span className="relative text-[10px] font-extrabold uppercase tracking-[0.14em] text-[#4f744c]">Ritual step</span><h3 className="relative mt-5 max-w-32 text-xl font-semibold leading-5 tracking-[-0.03em] text-[#253a28]">{category}</h3><p className="relative mt-3 text-[10px] font-bold uppercase tracking-[0.12em] text-[#738374]">{catalogue.isLoading ? "Curating" : `${categoryCounts[category]} products`}</p></Link>)}</div></div></section>
    <section id="featured" className="container py-16 sm:py-24"><div className="grid gap-5 border-b border-[#dce6d7] pb-9 sm:grid-cols-[1fr_auto] sm:items-end"><div><p className="noura-eyebrow">The NOURA shelf</p><h2 className="mt-3 text-4xl font-semibold tracking-[-0.05em] text-[#253a28] sm:text-5xl">Start with the essentials.</h2></div><p className="max-w-sm text-sm leading-6 text-[#667567]">A focused edit of routines, textures, and small daily moments worth keeping.</p></div><div className="mt-10">{catalogue.isLoading ? <ProductSkeletonGrid label="Building your everyday shelf…" /> : catalogue.error ? <CatalogueRecovery onRetry={() => catalogue.refetch()} /> : <ProductGrid products={productsForSection(featured)} />}</div></section>
  </main><StoreFooter /><CartDrawer /></div>;
}
