import React, { useState } from "react";
import { Link } from "wouter";
import { ArrowUpRight, Box, ClipboardCheck, CreditCard, Leaf, PackageSearch, Settings2, ShieldCheck, Tags, Truck } from "lucide-react";
import { useAuth } from "@/_core/hooks/useAuth";
import { CartDrawer, formatEgp, StoreFooter, StoreHeader } from "@/components/storefront";
import { trpc } from "@/lib/trpc";
import { offerPlanningTasks, operationViews, orderFollowUpTasks, type OperationView } from "@/lib/operations";

function Guard({ title, detail }: { title: string; detail: string }) {
  return <div className="min-h-screen bg-[#fcfdf9]"><StoreHeader /><main className="container py-24 text-center"><ShieldCheck size={42} className="mx-auto text-[#4f744c]" /><h1 className="mt-5 text-4xl font-semibold text-[#253a28]">{title}</h1><p className="mx-auto mt-3 max-w-lg text-sm leading-7 text-[#667567]">{detail}</p><Link href="/account" className="noura-button-primary mt-7 inline-flex px-5 py-3 text-xs font-black uppercase tracking-[0.12em]">Return to account</Link></main><StoreFooter /></div>;
}

function ShopifyButton({ href, children }: { href?: string | null; children: React.ReactNode }) {
  return href ? <a href={href} target="_blank" rel="noreferrer" className="noura-button-primary inline-flex items-center gap-2 px-4 py-3 text-xs font-black uppercase tracking-[0.11em]">{children}<ArrowUpRight size={14} /></a> : <span className="inline-flex rounded-lg bg-[#eef4e9] px-4 py-3 text-xs font-bold text-[#667567]">Claim Shopify to continue</span>;
}

function TaskList({ tasks, emptyText }: { tasks: typeof orderFollowUpTasks; emptyText: string }) {
  return <div className="space-y-3">{tasks.length ? tasks.map((task, index) => <article key={task.title} className="flex gap-4 rounded-xl border border-[#dce6d7] bg-white p-4"><span className="grid h-8 w-8 shrink-0 place-items-center rounded-full bg-[#eef4e9] text-xs font-black text-[#4f744c]">0{index + 1}</span><div><div className="flex flex-wrap items-center gap-2"><h3 className="font-semibold text-[#253a28]">{task.title}</h3><span className="rounded-full bg-[#edf3e8] px-2 py-0.5 text-[9px] font-black uppercase tracking-[0.12em] text-[#4f744c]">{task.source}</span></div><p className="mt-1 text-sm leading-6 text-[#667567]">{task.detail}</p></div></article>) : <p className="rounded-xl border border-dashed border-[#dce6d7] p-6 text-sm text-[#667567]">{emptyText}</p>}</div>;
}

export default function NouraOperations() {
  const { user, loading: authLoading } = useAuth();
  const [view, setView] = useState<OperationView>("Overview");
  const isAdmin = user?.role === "admin" && !user?.requiresPasswordChange;
  const overview = trpc.admin.overview.useQuery(undefined, { enabled: isAdmin, retry: 1 });
  const data = overview.data;
  const adminUrl = data?.shopifyAdminUrl;

  if (authLoading) return <Guard title="Opening NOURA Operations" detail="Your administrator access is being checked before live catalogue data is shown." />;
  if (!user) return <Guard title="Sign in to access NOURA Operations" detail="Use your NOURA account to open the protected operations workspace." />;
  if (!isAdmin) return <Guard title="Administrator access required" detail="NOURA Operations is available only to verified administrators with an updated password." />;

  const renderView = () => {
    if (overview.isLoading) return <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3" aria-busy="true">{Array.from({ length: 6 }).map((_, index) => <div key={index} className="noura-loading-shimmer h-36 rounded-xl" />)}</div>;
    if (overview.error || !data) return <div className="rounded-2xl border border-[#dce6d7] bg-white p-8 text-center"><PackageSearch size={30} className="mx-auto text-[#4f744c]" /><h2 className="mt-4 text-2xl font-semibold text-[#253a28]">Operations data needs a moment.</h2><p className="mx-auto mt-2 max-w-lg text-sm leading-6 text-[#667567]">The live catalogue overview could not be reached. No product, order, or payment record was changed.</p><button onClick={() => overview.refetch()} className="noura-button-primary mt-6 px-5 py-3 text-xs font-black uppercase tracking-[0.12em]">Retry workspace</button></div>;
    if (view === "Catalogue") return <section className="grid gap-6 lg:grid-cols-[1fr_0.75fr]"><div className="rounded-2xl border border-[#dce6d7] bg-white p-6"><p className="noura-eyebrow">Live storefront read</p><h2 className="mt-2 text-3xl font-semibold text-[#253a28]">Catalogue health</h2><div className="mt-6 divide-y divide-[#edf2e9]">{data.products.length ? data.products.map(product => <div key={product.id} className="flex items-center gap-3 py-4"><img src={product.images[0]?.url} alt="" className="h-12 w-12 rounded-lg bg-[#edf3e8] object-cover" /><div className="min-w-0 flex-1"><p className="truncate font-semibold text-[#253a28]">{product.title}</p><p className="mt-0.5 text-xs text-[#667567]">{product.productType || "Uncategorised"}</p></div><span className="text-xs font-black text-[#405642]">{formatEgp(product.priceRange.min)}</span></div>) : <p className="py-8 text-sm text-[#667567]">No published products are visible yet.</p>}</div></div><aside className="rounded-2xl bg-[#253a28] p-6 text-white"><Box size={22} className="text-[#b9d4b4]" /><h2 className="mt-5 text-3xl font-semibold">Catalogue actions</h2><p className="mt-3 text-sm leading-6 text-[#c3d3bf]">Titles, price, category, media, inventory, and publication are edited in Shopify so the live record remains consistent.</p><div className="mt-6"><ShopifyButton href={adminUrl ? `${adminUrl}/products` : null}>Open products</ShopifyButton></div></aside></section>;
    if (view === "Offers") return <section className="grid gap-6 lg:grid-cols-[1fr_0.75fr]"><div><p className="noura-eyebrow">Promotion planning</p><h2 className="mt-2 text-3xl font-semibold text-[#253a28]">Plan carefully, publish once</h2><p className="mt-3 max-w-2xl text-sm leading-6 text-[#667567]">NOURA does not mirror active codes into the storefront. This prevents an unpublished or expired offer from being presented to customers.</p><div className="mt-6"><TaskList tasks={offerPlanningTasks} emptyText="No promotion tasks are currently planned." /></div></div><aside className="rounded-2xl border border-[#dce6d7] bg-white p-6"><Tags size={22} className="text-[#4f744c]" /><h3 className="mt-5 text-2xl font-semibold text-[#253a28]">Offers live in Shopify</h3><p className="mt-3 text-sm leading-6 text-[#667567]">Create discount scope, dates, limits, and combinations where checkout will enforce them.</p><div className="mt-6"><ShopifyButton href={adminUrl ? `${adminUrl}/discounts` : null}>Open discounts</ShopifyButton></div></aside></section>;
    if (view === "Orders") return <section className="grid gap-6 lg:grid-cols-[1fr_0.75fr]"><div><p className="noura-eyebrow">Order follow-up</p><h2 className="mt-2 text-3xl font-semibold text-[#253a28]">Follow the source of truth</h2><p className="mt-3 max-w-2xl text-sm leading-6 text-[#667567]">Order numbers, payment status, addresses, and fulfilment remain exclusively in Shopify. NOURA does not cache them, so its interface never presents a stale customer order as current.</p><div className="mt-6"><TaskList tasks={orderFollowUpTasks} emptyText="No order follow-up is queued." /></div></div><aside className="rounded-2xl border border-[#dce6d7] bg-white p-6"><ClipboardCheck size={22} className="text-[#4f744c]" /><h3 className="mt-5 text-2xl font-semibold text-[#253a28]">No copied order data</h3><p className="mt-3 text-sm leading-6 text-[#667567]">Use the dedicated Shopify order record to view or update payment and fulfilment. This is intentional customer-data protection.</p><div className="mt-6"><ShopifyButton href={adminUrl ? `${adminUrl}/orders` : null}>Open orders</ShopifyButton></div></aside></section>;
    if (view === "Settings") return <section className="grid gap-4 sm:grid-cols-2"><article className="rounded-2xl border border-[#dce6d7] bg-white p-6"><CreditCard size={22} className="text-[#4f744c]" /><h2 className="mt-5 text-2xl font-semibold text-[#253a28]">Payments & checkout</h2><p className="mt-3 text-sm leading-6 text-[#667567]">Choose payment methods and review checkout directly in Shopify. NOURA never handles card details.</p><div className="mt-6"><ShopifyButton href={adminUrl ? `${adminUrl}/settings/payments` : null}>Open payments</ShopifyButton></div></article><article className="rounded-2xl border border-[#dce6d7] bg-white p-6"><Truck size={22} className="text-[#4f744c]" /><h2 className="mt-5 text-2xl font-semibold text-[#253a28]">Shipping & delivery</h2><p className="mt-3 text-sm leading-6 text-[#667567]">Set Egyptian zones, rates, delivery estimates, and fulfilment locations in Shopify before taking orders.</p><div className="mt-6"><ShopifyButton href={adminUrl ? `${adminUrl}/settings/shipping` : null}>Open shipping</ShopifyButton></div></article></section>;
    return <><section className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4"><article className="rounded-xl border border-[#dce6d7] bg-white p-5"><Box size={18} className="text-[#4f744c]" /><p className="mt-7 text-3xl font-semibold text-[#253a28]">{data.catalog.totalProducts}</p><p className="mt-1 text-[10px] font-black uppercase tracking-[0.14em] text-[#667567]">Live products</p></article><article className="rounded-xl border border-[#dce6d7] bg-white p-5"><Tags size={18} className="text-[#4f744c]" /><p className="mt-7 text-3xl font-semibold text-[#253a28]">{data.catalog.discountedProducts}</p><p className="mt-1 text-[10px] font-black uppercase tracking-[0.14em] text-[#667567]">Sale-priced products</p></article><article className="rounded-xl border border-[#dce6d7] bg-white p-5"><Leaf size={18} className="text-[#4f744c]" /><p className="mt-7 text-3xl font-semibold text-[#253a28]">{data.catalog.activeCategories}</p><p className="mt-1 text-[10px] font-black uppercase tracking-[0.14em] text-[#667567]">Active categories</p></article><article className="rounded-xl border border-[#dce6d7] bg-white p-5"><ShieldCheck size={18} className="text-[#4f744c]" /><p className="mt-7 text-sm font-semibold text-[#253a28]">Shopify</p><p className="mt-1 text-[10px] font-black uppercase tracking-[0.14em] text-[#667567]">Checkout & order truth</p></article></section><section className="mt-8 grid gap-4 lg:grid-cols-3"><article className="rounded-2xl border border-[#dce6d7] bg-white p-6"><Box size={21} className="text-[#4f744c]" /><h2 className="mt-5 text-2xl font-semibold text-[#253a28]">Catalogue</h2><p className="mt-2 text-sm leading-6 text-[#667567]">See the live edit, then manage products in Shopify.</p><button onClick={() => setView("Catalogue")} className="mt-5 text-xs font-black uppercase tracking-[0.12em] text-[#4f744c]">Review catalogue →</button></article><article className="rounded-2xl border border-[#dce6d7] bg-white p-6"><Tags size={21} className="text-[#4f744c]" /><h2 className="mt-5 text-2xl font-semibold text-[#253a28]">Offers</h2><p className="mt-2 text-sm leading-6 text-[#667567]">Plan promotion terms before publishing an enforceable Shopify offer.</p><button onClick={() => setView("Offers")} className="mt-5 text-xs font-black uppercase tracking-[0.12em] text-[#4f744c]">Plan offers →</button></article><article className="rounded-2xl border border-[#dce6d7] bg-white p-6"><ClipboardCheck size={21} className="text-[#4f744c]" /><h2 className="mt-5 text-2xl font-semibold text-[#253a28]">Orders</h2><p className="mt-2 text-sm leading-6 text-[#667567]">Use a clear handoff process without duplicating private order data.</p><button onClick={() => setView("Orders")} className="mt-5 text-xs font-black uppercase tracking-[0.12em] text-[#4f744c]">Review workflow →</button></article></section></>;
  };

  return <div className="min-h-screen bg-[#f7faf4]"><StoreHeader /><main className="container py-10 sm:py-14"><div className="flex flex-col gap-5 border-b border-[#dce6d7] pb-8 lg:flex-row lg:items-end lg:justify-between"><div><p className="noura-eyebrow">NOURA Operations</p><h1 className="mt-2 text-4xl font-semibold tracking-[-0.055em] text-[#253a28] sm:text-5xl">One calm place to run the store.</h1><p className="mt-3 max-w-2xl text-sm leading-6 text-[#667567]">Plan and review operations in NOURA. Product, offer, order, payment, and fulfilment records are protected in Shopify where the live transaction happens.</p></div><Link href="/admin" className="noura-button-secondary inline-flex w-fit px-4 py-3 text-xs font-black uppercase tracking-[0.11em]">Admin overview</Link></div><nav className="noura-scrollbar mt-7 flex gap-2 overflow-x-auto border-b border-[#dce6d7] pb-4" aria-label="NOURA Operations views">{operationViews.map(item => <button key={item} onClick={() => setView(item)} aria-pressed={view === item} className={`rounded-lg px-4 py-2 text-xs font-black uppercase tracking-[0.11em] transition ${view === item ? "bg-[#253a28] text-white" : "bg-white text-[#405642] hover:bg-[#eef4e9]"}`}>{item}</button>)}</nav><div className="mt-8">{renderView()}</div></main><StoreFooter /><CartDrawer /></div>;
}
